CREATE TYPE "public"."airtable_clone_column_type" AS ENUM('text', 'number', 'singleSelect', 'attachment');--> statement-breakpoint
CREATE TABLE "airtable_clone_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "airtable_clone_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "airtable_clone_bases" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"owner_id" text NOT NULL,
	"workspace_id" uuid NOT NULL,
	"name" text NOT NULL,
	"starred" boolean DEFAULT false NOT NULL,
	"last_modified_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "airtable_clone_columns" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"table_id" uuid NOT NULL,
	"name" text NOT NULL,
	"type" "airtable_clone_column_type" NOT NULL,
	"order_index" integer DEFAULT 0 NOT NULL,
	"is_hidden" boolean DEFAULT false NOT NULL,
	"config" jsonb
);
--> statement-breakpoint
CREATE TABLE "airtable_clone_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "airtable_clone_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "airtable_clone_rows" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"table_id" uuid NOT NULL,
	"index" integer NOT NULL,
	"values" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "airtable_clone_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "airtable_clone_tables" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"base_id" uuid NOT NULL,
	"name" text NOT NULL,
	"order_index" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "airtable_clone_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "airtable_clone_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "airtable_clone_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
CREATE TABLE "airtable_clone_workspaces" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"owner_id" text NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "airtable_clone_account" ADD CONSTRAINT "airtable_clone_account_userId_airtable_clone_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."airtable_clone_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "airtable_clone_bases" ADD CONSTRAINT "airtable_clone_bases_workspace_id_airtable_clone_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."airtable_clone_workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "airtable_clone_columns" ADD CONSTRAINT "airtable_clone_columns_table_id_airtable_clone_tables_id_fk" FOREIGN KEY ("table_id") REFERENCES "public"."airtable_clone_tables"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "airtable_clone_post" ADD CONSTRAINT "airtable_clone_post_createdById_airtable_clone_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."airtable_clone_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "airtable_clone_rows" ADD CONSTRAINT "airtable_clone_rows_table_id_airtable_clone_tables_id_fk" FOREIGN KEY ("table_id") REFERENCES "public"."airtable_clone_tables"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "airtable_clone_session" ADD CONSTRAINT "airtable_clone_session_userId_airtable_clone_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."airtable_clone_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "airtable_clone_tables" ADD CONSTRAINT "airtable_clone_tables_base_id_airtable_clone_bases_id_fk" FOREIGN KEY ("base_id") REFERENCES "public"."airtable_clone_bases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "airtable_clone_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "bases_owner_idx" ON "airtable_clone_bases" USING btree ("owner_id");--> statement-breakpoint
CREATE INDEX "bases_workspace_idx" ON "airtable_clone_bases" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "bases_owner_starred_idx" ON "airtable_clone_bases" USING btree ("owner_id","starred");--> statement-breakpoint
CREATE INDEX "bases_last_modified_idx" ON "airtable_clone_bases" USING btree ("owner_id","last_modified_at");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "airtable_clone_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "airtable_clone_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "rows_table_index_idx" ON "airtable_clone_rows" USING btree ("table_id","index");--> statement-breakpoint
CREATE INDEX "rows_table_id_idx" ON "airtable_clone_rows" USING btree ("table_id");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "airtable_clone_session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "workspaces_owner_idx" ON "airtable_clone_workspaces" USING btree ("owner_id");--> statement-breakpoint
CREATE INDEX "workspaces_owner_name_idx" ON "airtable_clone_workspaces" USING btree ("owner_id","name");